language: ruby
rvm:
  - 2.7

services:
  - docker

env:
  - spec=spec:rubygems
  - spec=spec:gradle_build
  - spec=spec:apt_install
  - spec=spec:yum_install
  - spec=spec:brew_install
  - spec=spec:cli
  - spec=spec:api
  - spec=spec:curl_api
  - spec=spec:npm_install
  - spec=spec:dotnet_build
  - spec=spec:maven_build
  - spec=spec:go_build

before_install:
  - gem install bundler:2.2.20

script:
  - bundle exec rake $spec
