language: ruby
services:
  - docker

env:
  - spec=spec:rubygems
  - spec=spec:apt_install
  - spec=spec:yum_install
  - spec=spec:brew_install
  - spec=spec:cli
  - spec=spec:api
  - spec=spec:npm_module_use
  - spec=spec:dotnet_build
  - spec=spec:gradle_build

script:
  - bundle exec rake $spec
