#!/usr/bin/env bash

source $(dirname $0)/functions

parse_exec_args "$1"

export FURYNIX_SOURCE_URL=$source_url

if [ -n "$gemfile" ]; then
    export BUNDLE_GEMFILE=$gemfile
fi

cd /build/app_using_gem
exec_cmd "bundle"
exec_cmd "rake"
