#!/usr/bin/env bash

source $(dirname $0)/functions

out_file="$1"
gemfile="$2"

if [ -n "$gemfile" ]; then
    export BUNDLE_GEMFILE=$gemfile
fi

cd /build/app_using_gem
exec_cmd "bundle"
exec_cmd "rake"
