#!/usr/bin/env bash

source $(dirname $0)/functions

parse_exec_args "$1"

detect_if_debian_wheezy
prepare_apt

if [ -n "$version" ]; then
    exec_cmd "$apt install -y gemfury=$version"
else
    exec_cmd "$apt install -y gemfury"
fi

exec_cmd "which ruby"
exec_cmd "ruby -v"

fury_path=$(which fury)
exec_cmd "echo $fury_path" $out_file
exec_cmd "$fury_path -v" $out_file
