#!/usr/bin/env bash

source $(dirname $0)/functions

parse_exec_args "$1"

exec_cmd "sudo apt -y update"
exec_cmd "sudo apt install -y ruby"
exec_cmd "which ruby"
exec_cmd "ruby -v"

exec_cmd "git -C \"/home/linuxbrew/.linuxbrew/Homebrew\" remote set-url origin https://github.com/Homebrew/brew"
exec_cmd "brew cleanup"
exec_cmd "brew update"

exec_cmd "brew tap $source"

if [ -n "$devel" ]; then
    exec_cmd "brew install --devel gemfury"
else
    exec_cmd "brew install gemfury"
fi

fury_path=$(which fury)
exec_cmd "echo $fury_path" $out_file
exec_cmd "$fury_path -v" $out_file
