#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

exec_cmd "apt update"
exec_cmd "apt install -yy curl"

exec_cmd "curl --fail -X GET \
            -H 'Accept: application/vnd.fury.v1+json' \
            https://$furynix_token@api.fury.io/gems/$gem/versions | grep '$version'"
