#!/usr/bin/env bash

source $(dirname $0)/functions

parse_exec_args "$1"

configure_furynix_token

exec_cmd "apt update"
exec_cmd "apt install -yy curl"
exec_cmd "curl -X GET -H 'Accept: application/vnd.fury.v1+json' https://$furynix_token@api.fury.io/users/me"
