#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

exec_cmd "curl --fail -X PUT \
            -H 'Accept: application/vnd.fury.v1+json' \
            -H 'Authorization: $furynix_token' \
            https://api.fury.io/collaborators/$(rawurlencode $user1)"

exec_cmd "curl --fail -s -X GET \
            -H 'Accept: application/vnd.fury.v1+json' \
            -H 'Authorization: $furynix_token' \
            https://api.fury.io/collaborators | grep '$user1'"

exec_cmd "curl --fail -X DELETE \
           -H 'Accept: application/vnd.fury.v1+json' \
           -H 'Authorization: $furynix_token' \
           https://api.fury.io/collaborators/$(rawurlencode $user1)"

exec_cmd "curl --fail -s -X GET \
            -H 'Accept: application/vnd.fury.v1+json' \
            -H 'Authorization: $furynix_token' \
            https://api.fury.io/collaborators | grep '$user1'" "" 1
