#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

exec_cmd "apt update"
exec_cmd "apt install -yy curl"

exec_cmd "curl --fail -X PUT \
            -H 'Accept: application/vnd.fury.v1+json' \
            https://$furynix_token@api.fury.io/collaborators/$(rawurlencode $email1)"

exec_cmd "curl --fail -s -X GET \
            -H 'Accept: application/vnd.fury.v1+json' \
            https://$furynix_token@api.fury.io/collaborators | grep '$user1'"

exec_cmd "curl --fail -X DELETE \
           -H 'Accept: application/vnd.fury.v1+json' \
           https://$furynix_token@api.fury.io/collaborators/$(rawurlencode $email1)"

exec_cmd "curl --fail -s -X GET \
            -H 'Accept: application/vnd.fury.v1+json' \
            https://$furynix_token@api.fury.io/collaborators | grep '$user1'" "" 1
