#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token
prepare_nuget

exec_cmd "whoami"
exec_cmd "mono -V"

cd /build/DotNetWorld
exec_cmd "rm -rf bin obj"
exec_cmd "dotnet build"
exec_cmd "dotnet pack"
exec_cmd "ls -fl $package_path"

exec_cmd "curl --fail -F package=@$package_path https://$furynix_token@push.fury.io/$furynix_user/"
sleep 5

exec_cmd "$nuget sources -NonInteractive -Format Short -ConfigFile $nuget_config"
exec_cmd "$nuget list Gemfury -NonInteractive -ConfigFile $nuget_config" $out_file
