#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

cd /build/DotNetHello
exec_cmd "rm -rf bin obj"
exec_cmd "dotnet restore"
exec_cmd "dotnet build"
exec_cmd "dotnet run" $out_file
