#!/usr/bin/env bash

source $(dirname $0)/functions

parse_exec_args "$1"

configure_furynix_token

cd /build/DotNetWorld
exec_cmd "rm -rf bin obj"
exec_cmd "dotnet build"
exec_cmd "dotnet pack"
exec_cmd "ls -fl $package_path" $out_file

exec_cmd "curl -X DELETE https://$furynix_token@api.fury.io/gems/$package_name/versions/$package_version -H 'Accept: application/vnd.fury.v1+json'"

exec_cmd "curl --fail -F package=@$package_path https://$furynix_token@push.fury.io/furynix2/" $out_file
