#!/usr/bin/env bash

source $(dirname $0)/functions

parse_exec_args "$1"

configure_furynix_token
detect_and_adjust_for_ruby19

if [ -n "$gemfile" ]; then
    export BUNDLE_GEMFILE=$gemfile
fi

cd /build/gem_using_bundler
exec_cmd "bundle"
exec_cmd "rake"

export BUNDLE_GEM__PUSH_KEY=fury
export RUBYGEMS_HOST=$push_url
export GEM_USING_BUNDLER_VERSION=$build_version
exec_cmd "rake build_and_release_fury"
