#!/usr/bin/env bash

source $(dirname $0)/functions

out_file="$1"
furynix_token="$2"
gemfile="$3"

configure_furynix_token
detect_and_adjust_for_ruby19

if [ -n "$gemfile" ]; then
    export BUNDLE_GEMFILE=$gemfile
fi

cd /build/gem_using_bundler
exec_cmd "bundle"
exec_cmd "rake"

export FURYNIX_API_TOKEN="$furynix_token"
export BUNDLE_GEM__PUSH_KEY=fury
exec_cmd "rake build_and_release_fury"
