#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

cd /build/jgo
exec_cmd "go test"

exec_cmd "rm -rf .git"
exec_cmd "tar -xzf git_clean.tgz"
exec_cmd "git remote add fury https://git.fury.io/$furynix_user/jgo.git"

exec_cmd "git add 1.1.0-delta && git commit -m 'Increment version 1.1.0'"

exec_cmd "git tag v$package_version"
exec_cmd "git push -f fury tags/v$package_version"
exec_cmd "git push -f fury master"
