#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

export ORG_GRADLE_PROJECT_furyUser="$FURYNIX_USER"
export ORG_GRADLE_PROJECT_furyToken="$FURYNIX_API_TOKEN"

cd /build/jworld
exec_cmd "rm -rf .gradle build"
exec_cmd "gradle -i build"
exec_cmd "gradle -i test"
exec_cmd "gradle -i publishAllPublicationsToThisRepository"
exec_cmd "ls -fl $package_path" $out_file

exec_cmd "curl --fail -F package=@$package_path https://$furynix_token@push.fury.io/$furynix_user/" $out_file
