#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

export ORG_GRADLE_PROJECT_furyUser="$FURYNIX_USER"
export ORG_GRADLE_PROJECT_furyToken="$furynix_deploy_token"

cd /build/hworld
exec_cmd "rm -rf .gradle build"
exec_cmd "gradle -i build -b $BUILD_FILE"
exec_cmd "gradle -i test -b $BUILD_FILE"
