#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

export ORG_GRADLE_PROJECT_furyUser="$FURYNIX_USER"
export ORG_GRADLE_PROJECT_furyToken="$FURYNIX_API_TOKEN"
export ORG_GRADLE_PROJECT_furyPushEndpoint="$FURYNIX_PUSH_ENDPOINT"

cd /build/nworld
exec_cmd "rm -rf .gradle build jhello/build jworld/build"
exec_cmd "gradle -i build"
exec_cmd "gradle -i test"
exec_cmd "gradle -i publishAllPublicationsToFuryRepository"
