#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

cd /build/jworld
exec_cmd "rm -rf target"
exec_cmd "mvn compile"
exec_cmd "mvn test"
exec_cmd "mvn package"
exec_cmd "ls -fl $package_path" $out_file

exec_cmd "curl --fail -F package=@$package_path https://$furynix_token@push.fury.io/$furynix_user/" $out_file
