#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

export FURYNIX_MAVEN_REPO_ID=fury
prepare_maven

cd /build/hworld
exec_cmd "rm -rf target"
exec_cmd "mvn compile -f $POM_FILE"
exec_cmd "mvn test -f $POM_FILE"
