#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token

export FURYNIX_MAVEN_REPO_ID=fury-push
export FURYNIX_MAVEN_TOKEN="$furynix_push_token"

prepare_maven

cd /build/nworld
exec_cmd "rm -rf target jhello/target jworld/target"
exec_cmd "mvn compile"
exec_cmd "mvn test"
exec_cmd "mvn deploy"
