#!/usr/bin/env bash

source $(dirname $0)/functions

configure_furynix_token
prepare_npm

exec_cmd "which node"
exec_cmd "node -v"
exec_cmd "which npm"
exec_cmd "npm -v"

mkdir /tmp/module_using_npm
cp -rf /build/module_using_npm/* /tmp/module_using_npm
rm -rf /tmp/module_using_npm/node_modules

cd /tmp/module_using_npm
exec_cmd "npm install"
exec_cmd "npm test"

if [ -z $dist_tag ]; then
    exec_cmd "npm publish"
else
    exec_cmd "npm publish --tag $dist_tag"
fi
