#!/usr/bin/env bash

source $(dirname $0)/functions

parse_exec_args "$1"

detect_and_adjust_for_ruby19

exec_cmd "which ruby"
exec_cmd "ruby -v"
exec_cmd "which gem"
exec_cmd "gem -v"

if [ ! -z "$thor_version" ]; then
    exec_cmd "gem install thor -v $thor_version"
fi

if [ ! -z "$faraday_version" ]; then
    exec_cmd "gem install faraday -v $faraday_version"
fi

if [ -n "$dev_version" ]; then
    exec_cmd "gem list --source $source gemfury --remote --prerelease"
    exec_cmd "gem install -V --source $source gemfury -v $dev_version --prerelease"
else
    exec_cmd "gem list --source $source gemfury --remote"
    exec_cmd "gem install --source $source gemfury"
fi

fury_path=$(which fury)
exec_cmd "echo $fury_path" $out_file
exec_cmd "$fury_path -v" $out_file
