#!/usr/bin/env bash

source $(dirname $0)/functions

prepare_yum

# enable the following, to use ruby24
# source /opt/rh/rh-ruby24/enable

if [ -n "$version" ]; then
    exec_cmd "yum install -y which gemfury-$version"
else
    exec_cmd "yum install -y which gemfury"
fi

exec_cmd "which ruby"
exec_cmd "ruby -v"

fury_path=$(which fury)
exec_cmd "echo $fury_path" $out_file
exec_cmd "$fury_path -v" $out_file
